apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: product-service-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "product-service.apps.{{ .Values.route_hostname }}"