name: product-service

on:
  push:
    branches: [ master ]
    paths:
      - product-service/**
      - .github/workflows/product-service.yml
  pull_request:
    branches: [ master ]
    paths:
      - product-service/**
      - .github/workflows/product-service.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jacobsee/s2i-github-action@master
      with:
        path: product-service
        base: registry.access.redhat.com/ubi8/openjdk-11
        output_image: quay.io/cloudfirst/product-service:latest
        image_push_registry: quay.io
        image_push_username: ${{ secrets.DOCKER_USERNAME }}
        image_push_password: ${{ secrets.DOCKER_PASSWORD }}